Rscript -e "Rcpp::compileAttributes()" && MAKE="make -j8" R CMD install --preclean .
Rscript testVB.R BayesC cattle Fpro 1
Rscript testVB.R BayesC cattle Fpro 2
Rscript testVB.R BayesC cattle Fpro 3
Rscript testVB.R BayesC cattle Fpro 4
Rscript testVB.R BayesC cattle Fpro 5
Rscript testVB.R BayesC cattle Fpro 6
Rscript testVB.R BayesC cattle Fpro 7
Rscript testVB.R BayesC cattle Fpro 8
Rscript testVB.R BayesC cattle Fpro 9
Rscript testVB.R BayesC cattle Fpro 10
Rscript testVB.R BayesC cattle Fpro 11
Rscript testVB.R BayesC cattle Fpro 12
Rscript testVB.R BayesC cattle Fpro 13
Rscript testVB.R BayesC cattle Fpro 14
Rscript testVB.R BayesC cattle Fpro 15
Rscript testVB.R BayesC cattle Fpro 16
Rscript testVB.R BayesC cattle Fpro 17
Rscript testVB.R BayesC cattle Fpro 18
Rscript testVB.R BayesC cattle Fpro 19
Rscript testVB.R BayesC cattle Fpro 20