# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesRR <- function(y, X, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_BayesRR`, y, X, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

BayesA <- function(y, X, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_BayesA`, y, X, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

BayesBpi <- function(y, X, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesBpi`, y, X, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

BayesB <- function(y, X, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_BayesB`, y, X, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

BayesCpi <- function(y, X, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesCpi`, y, X, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

BayesC <- function(y, X, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_BayesC`, y, X, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

BayesLASSO <- function(y, X, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_BayesLASSO`, y, X, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

BayesR <- function(y, X, pi = NULL, fold = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesR`, y, X, pi, fold, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

conjgt <- function(sumstat, ldm, lambda = NULL, esp = 1e-6, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_conjgt`, sumstat, ldm, lambda, esp, outfreq, verbose)
}

cutwind <- function(chr, pos, bp) {
    .Call(`_hibayes_cutwind`, chr, pos, bp)
}

read_bed <- function(bfile, pBigMat, maxLine, d = FALSE, threads = 0L) {
    invisible(.Call(`_hibayes_read_bed`, bfile, pBigMat, maxLine, d, threads))
}

SBayesRR <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesRR`, sumstat, ldm, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

SBayesA <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesA`, sumstat, ldm, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

SBayesBpi <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesBpi`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

SBayesB <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesB`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

SBayesCpi <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesCpi`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

SBayesC <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesC`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

SBayesLASSO <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesLASSO`, sumstat, ldm, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, verbose)
}

SBayesR <- function(sumstat, ldm, pi = NULL, fold = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vara = NULL, dfvara = NULL, s2vara = NULL, vare = NULL, dfvare = NULL, s2vare = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesR`, sumstat, ldm, pi, fold, niter, nburn, windindx, wppa, vara, dfvara, s2vara, vare, dfvare, s2vare, outfreq, fixpi, verbose)
}

uniform_sample <- function(start = 0, end = 1) {
    .Call(`_hibayes_uniform_sample`, start, end)
}

norm_sample <- function(mean = 0, sd = 1) {
    .Call(`_hibayes_norm_sample`, mean, sd)
}

gamma_sample <- function(shape, scale) {
    .Call(`_hibayes_gamma_sample`, shape, scale)
}

invgamma_sample <- function(shape, scale) {
    .Call(`_hibayes_invgamma_sample`, shape, scale)
}

chisq_sample <- function(shape) {
    .Call(`_hibayes_chisq_sample`, shape)
}

invchisq_sample <- function(shape, scale) {
    .Call(`_hibayes_invchisq_sample`, shape, scale)
}

beta_sample <- function(a, b) {
    .Call(`_hibayes_beta_sample`, a, b)
}

t_sample <- function(shape) {
    .Call(`_hibayes_t_sample`, shape)
}

cauchy_sample <- function(location, scale) {
    .Call(`_hibayes_cauchy_sample`, location, scale)
}

exponential_sample <- function(scale) {
    .Call(`_hibayes_exponential_sample`, scale)
}

laplace_sample <- function(mean, scale) {
    .Call(`_hibayes_laplace_sample`, mean, scale)
}

rinvgaussian_sample <- function(mu, lambda) {
    .Call(`_hibayes_rinvgaussian_sample`, mu, lambda)
}

rdirichlet_sample <- function(n, x) {
    .Call(`_hibayes_rdirichlet_sample`, n, x)
}

BigStat <- function(pBigMat, threads = 0L) {
    .Call(`_hibayes_BigStat`, pBigMat, threads)
}

tXXmat_Geno <- function(pBigMat, chisq = 0L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno`, pBigMat, chisq, threads, verbose)
}

tXXmat_Geno_gwas <- function(pBigMat, gwasgeno, refindx, gwasindx, chisq = 0L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno_gwas`, pBigMat, gwasgeno, refindx, gwasindx, chisq, threads, verbose)
}

tXXmat_Chr <- function(pBigMat, chr, chisq = 0L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr`, pBigMat, chr, chisq, threads, verbose)
}

tXXmat_Chr_gwas <- function(pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq = 0L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr_gwas`, pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq, threads, verbose)
}

