# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bayes <- function(y, X, model, Pi, C = NULL, R = NULL, fold = NULL, niter = 50000L, nburn = 20000L, epsl_y_J = NULL, epsl_Gi = NULL, epsl_index = NULL, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, windindx = NULL, wppa = 0.01, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_Bayes`, y, X, model, Pi, C, R, fold, niter, nburn, epsl_y_J, epsl_Gi, epsl_index, vg, dfvg, s2vg, ve, dfve, s2ve, windindx, wppa, outfreq, threads, verbose)
}

SBayesD <- function(sumstat, ldm, model, Pi, niter = 50000L, nburn = 20000L, fold = NULL, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_SBayesD`, sumstat, ldm, model, Pi, niter, nburn, fold, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

SBayesS <- function(sumstat, ldm, model, Pi, niter = 50000L, nburn = 20000L, fold = NULL, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_SBayesS`, sumstat, ldm, model, Pi, niter, nburn, fold, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

conjgt_spa <- function(sumstat, ldm, lambda = NULL, esp = 1e-6, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_conjgt_spa`, sumstat, ldm, lambda, esp, outfreq, verbose)
}

conjgt_den <- function(sumstat, ldm, lambda = NULL, esp = 1e-6, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_conjgt_den`, sumstat, ldm, lambda, esp, outfreq, verbose)
}

cutwind <- function(chr, pos, bp) {
    .Call(`_hibayes_cutwind`, chr, pos, bp)
}

rMap_c <- function(map_file, out = NULL) {
    .Call(`_hibayes_rMap_c`, map_file, out)
}

read_bed <- function(bfile, pBigMat, maxLine, impt = TRUE, d = FALSE, threads = 0L) {
    invisible(.Call(`_hibayes_read_bed`, bfile, pBigMat, maxLine, impt, d, threads))
}

make_grm <- function(Z, inverse = FALSE, verbose = TRUE) {
    .Call(`_hibayes_make_grm`, Z, inverse, verbose)
}

make_ped <- function(pvec, svec, dvec, verbose = TRUE) {
    .Call(`_hibayes_make_ped`, pvec, svec, dvec, verbose)
}

make_Ainv <- function(s, d, verbose = TRUE) {
    .Call(`_hibayes_make_Ainv`, s, d, verbose)
}

geno_impute <- function(Ang, geno, threads) {
    .Call(`_hibayes_geno_impute`, Ang, geno, threads)
}

BigStat <- function(pBigMat, threads = 0L) {
    .Call(`_hibayes_BigStat`, pBigMat, threads)
}

tXXmat_Geno <- function(pBigMat, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno`, pBigMat, chisq, threads, verbose)
}

tXXmat_Geno_gwas <- function(pBigMat, gwasgeno, refindx, gwasindx, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno_gwas`, pBigMat, gwasgeno, refindx, gwasindx, chisq, threads, verbose)
}

tXXmat_Chr <- function(pBigMat, chr, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr`, pBigMat, chr, chisq, threads, verbose)
}

tXXmat_Chr_gwas <- function(pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr_gwas`, pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq, threads, verbose)
}

