# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesRR <- function(y, X, C = NULL, R = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_BayesRR`, y, X, C, R, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

BayesA <- function(y, X, C = NULL, R = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_BayesA`, y, X, C, R, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

BayesBpi <- function(y, X, C = NULL, R = NULL, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesBpi`, y, X, C, R, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, fixpi, verbose)
}

BayesB <- function(y, X, C = NULL, R = NULL, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_BayesB`, y, X, C, R, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

BayesCpi <- function(y, X, C = NULL, R = NULL, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesCpi`, y, X, C, R, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, fixpi, verbose)
}

BayesC <- function(y, X, C = NULL, R = NULL, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_BayesC`, y, X, C, R, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

BayesLASSO <- function(y, X, C = NULL, R = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_BayesLASSO`, y, X, C, R, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, verbose)
}

BayesR <- function(y, X, C = NULL, R = NULL, pi = NULL, fold = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, threads = 0L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_BayesR`, y, X, C, R, pi, fold, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, threads, fixpi, verbose)
}

SBayesRR_den <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesRR_den`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesA_den <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesA_den`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesBpi_den <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesBpi_den`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

SBayesB_den <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesB_den`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesCpi_den <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesCpi_den`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

SBayesC_den <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesC_den`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesLASSO_den <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesLASSO_den`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesR_den <- function(sumstat, ldm, pi = NULL, fold = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesR_den`, sumstat, ldm, pi, fold, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

SBayesRR_spa <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesRR_spa`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesA_spa <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesA_spa`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesBpi_spa <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesBpi_spa`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

SBayesB_spa <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesB_spa`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesCpi_spa <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesCpi_spa`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

SBayesC_spa <- function(sumstat, ldm, pi = 0.95, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesC_spa`, sumstat, ldm, pi, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesLASSO_spa <- function(sumstat, ldm, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_SBayesLASSO_spa`, sumstat, ldm, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, verbose)
}

SBayesR_spa <- function(sumstat, ldm, pi = NULL, fold = NULL, niter = 50000L, nburn = 20000L, windindx = NULL, wppa = 0.01, vg = NULL, dfvg = NULL, s2vg = NULL, ve = NULL, dfve = NULL, s2ve = NULL, outfreq = 100L, fixpi = FALSE, verbose = TRUE) {
    .Call(`_hibayes_SBayesR_spa`, sumstat, ldm, pi, fold, niter, nburn, windindx, wppa, vg, dfvg, s2vg, ve, dfve, s2ve, outfreq, fixpi, verbose)
}

conjgt_spa <- function(sumstat, ldm, lambda = NULL, esp = 1e-6, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_conjgt_spa`, sumstat, ldm, lambda, esp, outfreq, verbose)
}

conjgt_den <- function(sumstat, ldm, lambda = NULL, esp = 1e-6, outfreq = 100L, verbose = TRUE) {
    .Call(`_hibayes_conjgt_den`, sumstat, ldm, lambda, esp, outfreq, verbose)
}

cutwind <- function(chr, pos, bp) {
    .Call(`_hibayes_cutwind`, chr, pos, bp)
}

rMap_c <- function(map_file, out = NULL) {
    .Call(`_hibayes_rMap_c`, map_file, out)
}

read_bed <- function(bfile, pBigMat, maxLine, impt = TRUE, d = FALSE, threads = 0L) {
    invisible(.Call(`_hibayes_read_bed`, bfile, pBigMat, maxLine, impt, d, threads))
}

BigStat <- function(pBigMat, threads = 0L) {
    .Call(`_hibayes_BigStat`, pBigMat, threads)
}

tXXmat_Geno <- function(pBigMat, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno`, pBigMat, chisq, threads, verbose)
}

tXXmat_Geno_gwas <- function(pBigMat, gwasgeno, refindx, gwasindx, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Geno_gwas`, pBigMat, gwasgeno, refindx, gwasindx, chisq, threads, verbose)
}

tXXmat_Chr <- function(pBigMat, chr, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr`, pBigMat, chr, chisq, threads, verbose)
}

tXXmat_Chr_gwas <- function(pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq = NULL, threads = 0L, verbose = TRUE) {
    .Call(`_hibayes_tXXmat_Chr_gwas`, pBigMat, chr, gwasgeno, gwaschr, refindx, gwasindx, chisq, threads, verbose)
}

